name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ fromJson(secrets.CICDPIPLINE).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJson(secrets.CICDPIPLINE).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.CICDPIPLINE).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJson(secrets.CICDPIPLINE).tenantId }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.CICDPIPLINE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve tfplan
      - name: Terraform destroy
        run: terraform destroy -auto-approve
        
