name: Terraform Azure Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
permissions:
  contents: read

jobs:

  terraform:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3


    - name: Terraform Init
      working-directory: .
      run: terraform init


    - name: Terraform Format Check
      working-directory: .
      run: terraform fmt -check


    - name: Terraform Validate
      working-directory: .
      run: terraform validate


    - name: Terraform Plan
      working-directory: .
      run: terraform plan
